name: Update Current Time

on:
  schedule:
    - cron: '*/1 * * * *'  # runs every minute
  workflow_dispatch:  # Allows manual triggering

jobs:
  update_time:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Ensure full repository history for commits
          
      - name: Update time
        run: |
          date > currenttime.txt

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add currenttime.txt
          git commit -m "Update current time" || echo "No changes"
          git push origin HEAD:${{ github.ref }}
